from enum import Enum


class OrderState(Enum):
    RECEBIDO = "RECEBIDO"
    INTERPRETADO = "INTERPRETADO"
    AGUARDANDO_CONFIRMACAO = "AGUARDANDO_CONFIRMACAO"
    CONFIRMADO = "CONFIRMADO"  # Estado interno/transição
    EM_ELABORACAO = "EM_ELABORACAO"
    EM_ANALISE = "EM_ANALISE"
    DECISAO = "DECISAO"  # Estado interno de consolidação
    AGUARDANDO_DECISAO = "AGUARDANDO_DECISAO"
    EM_REVISAO = "EM_REVISAO"
    FINALIZANDO = "FINALIZANDO"
    FINALIZADO = "FINALIZADO"


class EventType(Enum):
    # Order
    ORDER_CREATED = "ORDER_CREATED"
    ORDER_COMPLETED = "ORDER_COMPLETED"

    # Intentions
    INTENTIONS_EXTRACTED = "INTENTIONS_EXTRACTED"
    INTENTIONS_CONFIRMED = "INTENTIONS_CONFIRMED"

    # Proposal
    PROPOSAL_CREATED = "PROPOSAL_CREATED"
    PROPOSAL_REVISED = "PROPOSAL_REVISED"

    # Analysis
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    ANALYSIS_FAILED = "ANALYSIS_FAILED"

    # Decisions
    CUSTOMER_DECISION_REQUIRED = "CUSTOMER_DECISION_REQUIRED"
    CUSTOMER_DECISION_RECEIVED = "CUSTOMER_DECISION_RECEIVED"

    # Workflow
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    STATE_CHANGED = "STATE_CHANGED"
    WORKFLOW_PAUSED = "WORKFLOW_PAUSED"
    WORKFLOW_RESUMED = "WORKFLOW_RESUMED"

    # Conflicts
    CONFLICT_FOUND = "CONFLICT_FOUND"
    NO_CONFLICT = "NO_CONFLICT"
    GOAL_CONFLICT_FOUND = "GOAL_CONFLICT_FOUND"

    # Revision
    REVISION_COMPLETED = "REVISION_COMPLETED"

    # Result
    FINAL_RESPONSE_CREATED = "FINAL_RESPONSE_CREATED"
    RESULT_READY = "RESULT_READY"


class ChipState(Enum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    WARNING = "WARNING"
    COMPLETED = "COMPLETED"
    WAITING = "WAITING"


class ChipCategory(Enum):
    INGREDIENT = "ingredient"
    GOAL = "goal"
    RESTRICTION = "restriction"
    PREFERENCE = "preference"
    EVENT = "event"
    CONFLICT = "conflict"
    PROGRESS = "progress"


class ProposalStatus(Enum):
    DRAFT = "DRAFT"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class AnalysisStatus(Enum):
    PENDING = "PENDING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"