"""add_fields_to_unknown_terms

Revision ID: 1ffb2b683b67
Revises: 279b941c5934
Create Date: 2026-07-21 13:48:57.808292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ffb2b683b67'
down_revision: Union[str, None] = '279b941c5934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unknown_terms', sa.Column('resolution', sa.String(length=20), nullable=True))
    op.add_column('unknown_terms', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('unknown_terms', sa.Column('suggestion', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('unknown_terms', 'suggestion')
    op.drop_column('unknown_terms', 'confidence')
    op.drop_column('unknown_terms', 'resolution')
    # ### end Alembic commands ###
