"""add_ingredient_catalog

Revision ID: 279b941c5934
Revises: 93a7dae09bbe
Create Date: 2026-07-20 15:44:58.937698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279b941c5934'
down_revision: Union[str, None] = '93a7dae09bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['ingredient_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredient_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('edible', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['ingredient_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ingredient_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_embeddings',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_catalog.id'], ),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('ingredient_extra_metadata',
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('nutritional_info', sa.JSON(), nullable=True),
    sa.Column('seasonality', sa.JSON(), nullable=True),
    sa.Column('custom_properties', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_catalog.id'], ),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('ingredient_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unknown_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=200), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_catalog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unknown_terms')
    op.drop_table('ingredient_sources')
    op.drop_table('ingredient_extra_metadata')
    op.drop_table('ingredient_embeddings')
    op.drop_table('ingredient_aliases')
    op.drop_table('ingredient_catalog')
    op.drop_table('ingredient_categories')
    # ### end Alembic commands ###
